baseURL = '/'
languageCode = 'en-us'
title = 'Santosh Kumar Gouda'
theme = 'archie'
copyright = '©santosh kumar gouda'

[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Random stuff and opinions"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sgouda0412"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/Gouda21K/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/sgouda0412/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
